spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    format:
      date: yyyy-MM-dd
  profiles:
    active: dev
logging:
  level:
    root: INFO
    com.epam.spring: DEBUG