spring:
  datasource:
    url: jdbc:h2:mem:cinema;
logging:
  level:
    root: INFO
    com.epam: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    java:
      enabled: true
    env:
      enabled: true
